vscode:
  extensions:
    - jcbuisson.vue@0.1.5:iY3UUCX2mmoIw5ODWkEcyw==
    - bradlc.vscode-tailwindcss@0.2.0:PwefoJooyem7BVrpU3Bjww==
    - CoenraadS.bracket-pair-colorizer@1.0.61:fqPT1sJEqaEdrfXeYbdW+A==
    - zhuangtongfa.Material-theme@2.28.3:v0Wk19l9g9nYeLBLTgzcLA==
    - esbenp.prettier-vscode@3.6.0:9y6m6ybLqFsrLdLgdncMCA==
    - oderwat.indent-rainbow@7.4.0:nth8lnJRnQu9NcWvNc9KPA==
    - formulahendry.auto-rename-tag@0.1.1:lKCmLIZAiCM0M8AjDnwCLQ==
    - vscode-icons-team.vscode-icons@9.5.0:dcvbiJm3ipHVkZXodLCtUA==
